name: 🥰 Auto update azl stories

on:
  push:
    branches:
      - main
  # auto update at 12:00 every day
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Check for updates (Should we run?)
        id: check_update
        run: |
          TARGET_REPO="https://github.com/AzurLaneTools/AzurLaneData.git"

          LATEST_SHA=$(git ls-remote "$TARGET_REPO" refs/heads/main | awk '{print $1}')
          echo "Sauce Repo last commit: $LATEST_SHA"

          git fetch origin web || echo "no web branch found!!!"
          PREV_SHA=$(git show origin/web:commit_id.txt 2>/dev/null || echo "none")
          echo "Our Repo last processed commit: $PREV_SHA"

          EVENT_NAME="${{ github.event_name }}"
          echo "This GH Action is Triggered by: $EVENT_NAME"

          if [ "$LATEST_SHA" != "$PREV_SHA" ] || [ "$EVENT_NAME" == "push" ] || [ "$EVENT_NAME" == "workflow_dispatch" ]; then
            echo "Sauce or Project Repo updated. AF 可能缺少淡水。"
            echo "DO_UPDATE=true" >> $GITHUB_OUTPUT
            echo "TARGET_SHA=$LATEST_SHA" >> $GITHUB_ENV 
          else
            echo "Sauce no change. Skip processing."
            echo "DO_UPDATE=false" >> $GITHUB_OUTPUT
          fi

      # only run if DO_UPDATE is true
      - name: Run sparse checkout script
        if: steps.check_update.outputs.DO_UPDATE == 'true'
        run: |
          chmod +x ./setup-source.sh
          ./setup-source.sh

      - name: Run main processing script
        if: steps.check_update.outputs.DO_UPDATE == 'true'
        run: |
          python3 src/main.py --overwrite

      - name: Push to web branch
        if: steps.check_update.outputs.DO_UPDATE == 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: web
          publish_dir: ./output
          user_name: "Bot"
          user_email: "268117545+jcxyis-bot[bot]@users.noreply.github.com"
          commit_message: "Auto update -> https://github.com/AzurLaneTools/AzurLaneData/commit/${{ env.TARGET_SHA }}"
